<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>1.4.9</Version>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ApplicationIcon>assets\network-monitor.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="installer/**/*.cs" />
    <Content Include="assets\network-monitor.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
